version: '3.9'

services:
  db:
    image: postgres:15
    container_name: cafe_postgres
    restart: always
    environment:
      POSTGRES_USER: cafe-factory
      POSTGRES_PASSWORD: myDream220321!
      POSTGRES_DB: cafe_bot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: